### ISSUE TITLE
Student Model is not being saved

### ISSUE THREAD

**Issue by raypretam** [amazon-science/dq-bart#4]
I am running the model using the following code according to the steps that are in the repo
```python3 run_summarization_no_trainer.py --model_name_or_path bart-base-cnn --dataset_name cnn_dailymail --dataset_config_name 3.0.0 --pred_distill --intermediate_distill --num_train_epochs 20 --weight_bits 8 --do_train --distill_encoder 3 --distill_decoder 1 --learning_rate 3e-5 --per_device_train_batch_size 8 --per_device_eval_batch_size 16 --output_dir output_cnn_dailymail/```

The error that is being show in as follows
```Traceback (most recent call last):
  File "run_summarization_no_trainer.py", line 896, in <module>
    main()
  File "run_summarization_no_trainer.py", line 822, in main
    unwrapped_model.save_pretrained(args.output_dir, save_function=accelerator.save)
  File "/home/aniruddha/anaconda3/envs/pretam/lib/python3.6/site-packages/transformers/modeling_utils.py", line 1068, in save_pretrained
    model_to_save.config.save_pretrained(save_directory)
  File "/home/aniruddha/anaconda3/envs/pretam/lib/python3.6/site-packages/transformers/configuration_utils.py", line 438, in save_pretrained
    self.to_json_file(output_config_file, use_diff=True)
TypeError: to_json_file() got an unexpected keyword argument 'use_diff'```

**Comment by zijwang** [comment]
@raypretam It might indicate a package version issue. You may try more latest transformers or simply remove ` use_diff=True` and retry.

**Comment by jmdu99** [comment]
I get the same error:

```
File "run_summarization_no_trainer.py", line 896, in <module>
    main()
File "run_summarization_no_trainer.py", line 822, in main
    unwrapped_model.save_pretrained(args.output_dir, save_function=accelerator.save)
File "/opt/conda/lib/python3.8/site-packages/transformers/modeling_utils.py", line 1068, in save_pretrained
    model_to_save.config.save_pretrained(save_directory)
File "/opt/conda/lib/python3.8/site-packages/transformers/configuration_utils.py", line 438, in save_pretrained
    self.to_json_file(output_config_file, use_diff=True)
TypeError: to_json_file() got an unexpected keyword argument 'use_diff'
```

I have tried to remove `use_diff=True` from `self.to_json_file(output_config_file, use_diff=True)` in `configuration_utils.py` but it didn't work.

Also, I notice that in later versions of `transformers`, `to_json_file()` has still the `use_diff` argument. So I don't really know how to solve the issue. 

Any help is appreciated @zijwang @raypretam

**Comment by raypretam** [comment]
@jmdu99 I installed a previous version of transformers and after removing the use_diff argument it worked. Moreover the repo does not work with custom datasets(I was testing with some local datasets).

**Comment by jmdu99** [comment]
Understood. Thanks for letting me know!
